---
# Default settings for all vms (they can be overridden on each node)
default:
  memory: 1612 # MB or RAM to assign - CentOS Installer needs at leas 1512 MB
  # box_url: 'http://cloud.centos.org/centos/8/x86_64/images/CentOS-8-Vagrant-8.4.2105-20210603.0.x86_64.vagrant-virtualbox.box'
  box: betadots/centos8p7 # Box used for the VM
  cpu: 1 # Number of vCPU to assign to the VM
  domain: betadots.training # Name of DNS domain for the created machines

# List of nodes shown in vagrant status
nodes:
  foreman:
    memory: 8192
    cpu: 4
    ip: 10.100.10.101
  docker:
    ip: 10.100.10.102
  apache:
    ip: 10.100.10.103
  host:
    ip: 10.100.10.104
    box: sridhav/empty
