---
# Default settings for all vms (they can be overridden on each node)
default:
  memory: 1612 # MB of RAM to assign - CentOS Installer needs at least 1512 MB
  box: boxomatic/centos-stream-9
  cpu: 1 # Number of vCPU to assign to the VM
  domain: betadots.training # Name of DNS domain for the created machines

# List of nodes shown in vagrant status
nodes:
  foreman:
    memory: 12288
    cpu: 6
    ip: 10.100.10.101
  # docker:
  #   ip: 10.100.10.102
  # apache:
  #   ip: 10.100.10.103
