---
# Default settings for all vms (they can be overridden on each node)
vm:
  memory: 1612                  # MB or RAM to assign
  cpu: 1                       # Number of vCPU to assign to the VM
  box: centos8                 # Box used for the VM, from the boxes list below

# A local network is created among the VM. Here is configured.
network:
  range: 10.100.10.0/24
  ip_start_offset: 101
  domain: betadots.training       # Name of DNS domain for the created machines

# Vagrant settings
vagrant:
  # Update host's /etc/hosts if you have the hostmanager plugin.
  hostmanager.manage_host: true # If true and you have the hostmanager plugin

# List of nodes shown in vagrant status
# Node names are based on the defined role. Here can be overridden vm defaults,
# it can be enforced a defined host name, added alieses, port forwarding
nodes:
  - role: foreman
    memory: 8192
    cpu: 4
  - role: docker
    count: 1
  - role: apache
    count: 1
  - role: host
    count: 1
    box: empty

# List of available Vagrant boxes with different OS to test on
boxes:
  centos8:
    box: centos/8
  empty:
    box: sridhav/empty
